trigger:
  branches:
    include:
      - 'refs/heads/microservices'

pool:
  name: 'Default'

variables:
  MAVEN_OPTS: '-Xmx1024m'

stages:
  - stage: Build
    jobs:
      - job: Build_Microservices
        displayName: 'Build Microservices'
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'eureka-server/pom.xml'  # Make sure this is the parent POM including all modules
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'

          # Check and publish each JAR artifact if it exists
          - script: |
              if [ -f eureka-server/target/*.jar ]; then
                echo "Eureka Server JAR exists."
              else
                echo "Eureka Server JAR does not exist."
                exit 1
              fi
          - publish: eureka-server/target/*.jar
            artifact: EurekaServer

          - script: |
              if [ -f gateway/target/*.jar ]; then
                echo "Gateway JAR exists."
              else
                echo "Gateway JAR does not exist."
                exit 1
              fi
          - publish: gateway/target/*.jar
            artifact: Gateway

          - script: |
              if [ -f config-server/target/*.jar ]; then
                echo "Config Server JAR exists."
              else
                echo "Config Server JAR does not exist."
                exit 1
              fi
          - publish: config-server/target/*.jar
            artifact: ConfigServer

          - script: |
              if [ -f auth-service/target/*.jar ]; then
                echo "Auth Service JAR exists."
              else
                echo "Auth Service JAR does not exist."
                exit 1
              fi
          - publish: auth-service/target/*.jar
            artifact: AuthService

          - script: |
              if [ -f user-service/target/*.jar ]; then
                echo "User Service JAR exists."
              else
                echo "User Service JAR does not exist."
                exit 1
              fi
          - publish: user-service/target/*.jar
            artifact: UserService

          - script: |
              if [ -f job-service/target/*.jar ]; then
                echo "Job Service JAR exists."
              else
                echo "Job Service JAR does not exist."
                exit 1
              fi
          - publish: job-service/target/*.jar
            artifact: JobService

          - script: |
              if [ -f notification-service/target/*.jar ]; then
                echo "Notification Service JAR exists."
              else
                echo "Notification Service JAR does not exist."
                exit 1
              fi
          - publish: notification-service/target/*.jar
            artifact: NotificationService

          - script: |
              if [ -f file-storage/target/*.jar ]; then
                echo "File Storage Service JAR exists."
              else
                echo "File Storage Service JAR does not exist."
                exit 1
              fi
          - publish: file-storage/target/*.jar
            artifact: FileStorageService
