trigger:
- main

pool:
  name: 'Default'  # Using the default agent pool

variables:
  MAVEN_OPTIONS: '-DskipTests'

jobs:
  - job: BuildAndTestMicroservices
    displayName: 'Build and Test Microservices'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        clean: 'true'
        displayName: 'Checkout Repository'

      # Building Eureka Server
      - task: Maven@4
        displayName: 'Build Eureka Server'
        inputs:
          mavenPomFile: 'eureka-server/pom.xml'
          goals: 'clean install $(MAVEN_OPTIONS)'

      # Building Gateway
      - task: Maven@4
        displayName: 'Build Gateway'
        inputs:
          mavenPomFile: 'gateway/pom.xml'
          goals: 'clean install $(MAVEN_OPTIONS)'

      # Add other Maven build steps for other services...

      # Debugging step to list files for troubleshooting
      - script: |
          echo "Listing files for debugging"
          ls -R $(Build.SourcesDirectory)
        displayName: 'List files for debugging'

  - job: ArchiveArtifacts
    displayName: 'Archive Build Artifacts'
    dependsOn: BuildAndTestMicroservices
    steps:
      # Publishing the built .jar files as artifacts
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Eureka Server Artifact'
        inputs:
          PathtoPublish: 'eureka-server/target/*.jar'
          ArtifactName: 'eureka-server'
          publishLocation: 'Container'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Gateway Artifact'
        inputs:
          PathtoPublish: 'gateway/target/*.jar'
          ArtifactName: 'gateway'
          publishLocation: 'Container'

      # Add more artifact publishing tasks as needed for other services

  - job: Cleanup
    displayName: 'Cleanup Workspace'
    dependsOn: BuildAndTestMicroservices
    steps:
      - task: DeleteFiles@1
        displayName: 'Delete Workspace Files'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: '**/*'
          RemoveSourceFolder: true
