trigger:
- microservices

pool:
  name: Default
  vmImage: 'ubuntu-latest'
  demands:
    - maven

variables:
  MAVEN_OPTIONS: '-DskipTests'

jobs:
- job: BuildAndTestMicroservices
  displayName: 'Build and Test Microservices'
  steps:
    - checkout: self
      displayName: 'Checkout Repository'

    - task: Maven@4
      displayName: 'Build Eureka Server'
      inputs:
        mavenPomFile: 'eureka-server/pom.xml'
        goals: 'clean install $(MAVEN_OPTIONS)'

    - task: Maven@4
      displayName: 'Build Gateway'
      inputs:
        mavenPomFile: 'gateway/pom.xml'
        goals: 'clean install $(MAVEN_OPTIONS)'

    - task: Maven@4
      displayName: 'Build Config Server'
      inputs:
        mavenPomFile: 'config-server/pom.xml'
        goals: 'clean install $(MAVEN_OPTIONS)'

    - task: Maven@4
      displayName: 'Build Auth Service'
      inputs:
        mavenPomFile: 'auth-service/pom.xml'
        goals: 'clean install $(MAVEN_OPTIONS)'

    - task: Maven@4
      displayName: 'Build User Service'
      inputs:
        mavenPomFile: 'user-service/pom.xml'
        goals: 'clean install $(MAVEN_OPTIONS)'

    - task: Maven@4
      displayName: 'Build Job Service'
      inputs:
        mavenPomFile: 'job-service/pom.xml'
        goals: 'clean install $(MAVEN_OPTIONS)'

    - task: Maven@4
      displayName: 'Build Notification Service'
      inputs:
        mavenPomFile: 'notification-service/pom.xml'
        goals: 'clean install $(MAVEN_OPTIONS)'

    - task: Maven@4
      displayName: 'Build File Storage Service'
      inputs:
        mavenPomFile: 'file-storage/pom.xml'
        goals: 'clean install $(MAVEN_OPTIONS)'

- job: ArchiveArtifacts
  displayName: 'Archive Build Artifacts'
  dependsOn: BuildAndTestMicroservices
  steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        PathtoPublish: '**/target/*.jar'
        ArtifactName: 'jarFiles'
        publishLocation: 'Container'

- job: Cleanup
  displayName: 'Cleanup Workspace'
  dependsOn: BuildAndTestMicroservices
  steps:
    - task: DeleteFiles@1
      displayName: 'Delete Workspace Files'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**/*'
        RemoveSourceFolder: true
