trigger:
- microservices
   
pool:
  name: 'Default'
   

variables:
  imageName: 'microservices/auth-service'
  DOCKER_BUILDKIT: 1
    
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile