trigger:
  branches:
    include:
      - 'refs/heads/microservices'

pool:
  name: 'Default'

variables:
  MAVEN_OPTS: '-Xmx1024m'

stages:
  - stage: Build
    jobs:
      - job: Build_Microservices
        displayName: 'Build Microservices'
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'eureka-server/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - script: |
              if [ -f eureka-server/target/*.jar ]; then
                echo "File exists."
              else
                echo "File does not exist."
                exit 1
              fi
          - publish: eureka-server/target/*.jar
            artifact: EurekaServer
          - script: |
              if [ -f gateway/target/*.jar ]; then
                echo "File exists."
              else
                echo "File does not exist."
                exit 1
              fi
          - publish: gateway/target/*.jar
            artifact: Gateway
          - script: |
              if [ -f config-server/target/*.jar ]; then
                echo "File exists."
              else
                echo "File does not exist."
                exit 1
              fi
          - publish: config-server/target/*.jar
            artifact: ConfigServer
          - script: |
              if [ -f auth-service/target/*.jar ]; then
                echo "File exists."
              else
                echo "File does not exist."
                exit 1
              fi
          - publish: auth-service/target/*.jar
            artifact: AuthService
          - script: |
              if [ -f user-service/target/*.jar ]; then
                echo "File exists."
              else
                echo "File does not exist."
                exit 1
              fi
          - publish: user-service/target/*.jar
            artifact: UserService
          - script: |
              if [ -f job-service/target/*.jar ]; then
                echo "File exists."
              else
                echo "File does not exist."
                exit 1
              fi
          - publish: job-service/target/*.jar
            artifact: JobService
          - script: |
              if [ -f notification-service/target/*.jar ]; then
                echo "File exists."
              else
                echo "File does not exist."
                exit 1
              fi
          - publish: notification-service/target/*.jar
            artifact: NotificationService
          - script: |
              if [ -f file-storage/target/*.jar ]; then
                echo "File exists."
              else
                echo "File does not exist."
                exit 1
              fi
          - publish: file-storage/target/*.jar
            artifact: FileStorageService

          - task: Maven@4
            inputs:
              mavenPomFile: 'file-storage/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - publish: config-server/target/*.jar
            artifact: ConfigServer

          - task: Maven@4
            inputs:
              mavenPomFile: 'auth-service/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - publish: auth-service/target/*.jar
            artifact: AuthService

          - task: Maven@4
            inputs:
              mavenPomFile: 'user-service/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - publish: user-service/target/*.jar
            artifact: UserService

          - task: Maven@4
            inputs:
              mavenPomFile: 'job-service/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - publish: job-service/target/*.jar
            artifact: JobService

          - task: Maven@4
            inputs:
              mavenPomFile: 'notification-service/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - publish: notification-service/target/*.jar
            artifact: NotificationService

          - task: Maven@4
            inputs:
              mavenPomFile: 'file-storage/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - publish: file-storage/target/*.jar
            artifact: FileStorageService