trigger:
  branches:
    include:
      - 'refs/heads/microservices'

pool:
  name: 'Default'

variables:
  MAVEN_OPTS: '-Xmx1024m'

stages:
  - stage: Build
    jobs:
      - job: Build_Microservices
        displayName: 'Build Microservices'
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'eureka-server/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - publish: eureka-server/target/*.jar
            artifact: EurekaServer

          - task: Maven@4
            inputs:
              mavenPomFile: 'gateway/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - publish: gateway/target/*.jar
            artifact: Gateway

          - task: Maven@4
            inputs:
              mavenPomFile: 'config-server/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - publish: config-server/target/*.jar
            artifact: ConfigServer

          - task: Maven@4
            inputs:
              mavenPomFile: 'auth-service/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - publish: auth-service/target/*.jar
            artifact: AuthService

          - task: Maven@4
            inputs:
              mavenPomFile: 'user-service/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - publish: user-service/target/*.jar
            artifact: UserService

          - task: Maven@4
            inputs:
              mavenPomFile: 'job-service/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - publish: job-service/target/*.jar
            artifact: JobService

          - task: Maven@4
            inputs:
              mavenPomFile: 'notification-service/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - publish: notification-service/target/*.jar
            artifact: NotificationService

          - task: Maven@4
            inputs:
              mavenPomFile: 'file-storage/pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              options: '-DskipTests'
          - publish: file-storage/target/*.jar
            artifact: FileStorageService