apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: wassimacrtest.azurecr.io/auth-service:latest
        ports:
        - containerPort: 8080  
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod" 
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret  
              key: "jdbc:postgresql://localhost:5432/microservice"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-password
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:  
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:  
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
