apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  labels:
    app: eureka-server
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: wassimacrtest.azurecr.io/eureka-server:latest  
        ports:
        - containerPort: 8761  
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"  
        - name: EUREKA_SERVER_HOSTNAME
          value: "eureka-server"  
        - name: EUREKA_SERVER_PORT
          value: "8761"  
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /eureka/apps
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /eureka/apps
            port: 8761
          initialDelaySeconds: 10
          periodSeconds: 10