apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 80         # Kubernetes internal service port
      targetPort: 8761  # Port the container listens on
  type: ClusterIP      # Service type (internal)
