apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service-deployment
  labels:
    app: job-service
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
      - name: job-service
        image: wassimacrtest.azurecr.io/job-service:latest  
        ports:
        - containerPort: 8080  
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"  
        - name: EUREKA_SERVER_URL
          value: "http://eureka-server:8761/eureka/"  
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
