apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 80         # Kubernetes internal service port
      targetPort: 8080  # Port the container listens on
  type: ClusterIP      # Service type (internal)