apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels:
    app: notification-service
spec:
  replicas: 3  # Number of replicas for high availability
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: <your-docker-registry>/notification-service:latest  # Replace with your image name
        ports:
        - containerPort: 8080  # Default notification-service port
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"  # Optional: Set Spring profiles
        - name: EUREKA_SERVER_URL
          value: "http://eureka-server:8761/eureka/"  # Replace with Eureka server URL if necessary
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
