apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80         # Kubernetes internal service port
      targetPort: 8080  # Port the container listens on
  type: ClusterIP      # Service type (internal)